"""Semantic Memory Store — LanceDB + nomic-embed-text via Ollama.

Four persistent tables (one per memory domain) stored in a local directory.
Embeddings are generated by the nomic-embed-text model running in Ollama,
keeping the orchestrator container lightweight.

Usage:
    store = SemanticMemoryStore(db_path="./memory_db", ollama_url="http://localhost:11434")
    await store.initialize()

    await store.store("spatial", "Charging dock at x=1.5, y=2.0", {"label": "charging_dock"})
    results = await store.query("spatial", "where is the charging station?", n_results=3)
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ── LanceDB / PyArrow imports ─────────────────────────────────────────
try:
    import lancedb
    import pyarrow as pa
    _LANCEDB_AVAILABLE = True
except ImportError:
    _LANCEDB_AVAILABLE = False
    logger.warning("lancedb / pyarrow not installed — SemanticMemoryStore will run in stub mode")

# ── Memory domain definitions ─────────────────────────────────────────

DOMAINS: dict[str, str] = {
    "spatial": "Waypoints, known obstacles, alternate routes, building layouts.",
    "behavioral": "Past human interactions, successful/failed commands, operator preferences.",
    "env_context": "Time-of-day lighting, crowd densities, scheduled maintenance windows.",
    "policy": "Custom rules like 'never drive near wet floor' or 'prioritize charging before long task'.",
}

# Vector dimensionality for nomic-embed-text
EMBED_DIM = 768

# Maximum chars returned in a single result summary
MAX_RESULT_CHARS = 800


@dataclass
class MemoryResult:
    """A single semantic memory search result."""
    doc_id: str
    text: str
    score: float  # cosine distance (lower = more similar)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: float = 0.0

    def to_summary(self) -> str:
        meta_str = json.dumps(self.metadata) if self.metadata else "{}"
        return f"[id={self.doc_id}] [score={self.score:.3f}] {self.text[:MAX_RESULT_CHARS]} | meta={meta_str}"


class SemanticMemoryStore:
    """Persistent semantic memory backed by LanceDB with per-domain tables.

    Each domain (spatial, behavioral, env_context, policy) has its own
    LanceDB table to prevent high-volume spatial data from inflating search
    latency for low-volume policy lookups.

    Embeddings are generated lazily via Ollama's /api/embed endpoint using
    the nomic-embed-text model — the same Ollama instance used for the VLA tool.
    """

    def __init__(
        self,
        db_path: str | Path = "./memory_db",
        ollama_url: str = "http://localhost:11434",
    ) -> None:
        self._db_path = Path(db_path)
        self._ollama_url = ollama_url.rstrip("/")
        self._db: Any = None  # lancedb.AsyncConnection
        self._tables: dict[str, Any] = {}  # domain → lancedb.AsyncTable
        self._initialized = False

    # ── Lifecycle ─────────────────────────────────────────────────────

    async def initialize(self) -> None:
        """Open (or create) the LanceDB database and ensure all tables exist."""
        if not _LANCEDB_AVAILABLE:
            logger.warning("SemanticMemoryStore: running in stub mode (no lancedb)")
            self._initialized = True
            return

        self._db_path.mkdir(parents=True, exist_ok=True)
        self._db = await lancedb.connect_async(str(self._db_path))

        schema = pa.schema([
            pa.field("doc_id",    pa.utf8()),
            pa.field("text",      pa.utf8()),
            pa.field("vector",    pa.list_(pa.float32(), EMBED_DIM)),
            pa.field("metadata",  pa.utf8()),   # JSON string
            pa.field("created_at", pa.float64()),
        ])

        existing = await self._db.table_names()
        for domain in DOMAINS:
            if domain not in existing:
                table = await self._db.create_table(domain, schema=schema)
                logger.info("SemanticMemoryStore: created table '%s'", domain)
            else:
                table = await self._db.open_table(domain)
                logger.info("SemanticMemoryStore: opened existing table '%s'", domain)
            self._tables[domain] = table

        self._initialized = True
        logger.info("SemanticMemoryStore: initialized at '%s'", self._db_path)

    async def shutdown(self) -> None:
        """No-op for LanceDB (connection is stateless)."""
        self._initialized = False

    # ── Embedding ─────────────────────────────────────────────────────

    async def _embed(self, text: str) -> list[float]:
        """Generate an embedding vector via Ollama nomic-embed-text."""
        import urllib.request

        payload = json.dumps({
            "model": "nomic-embed-text",
            "prompt": text,
        }).encode()

        url = f"{self._ollama_url}/api/embeddings"
        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        # Run the blocking HTTP call in a thread so we don't block the event loop
        def _do_request() -> list[float]:
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read())
            # Ollama /api/embed returns {"embeddings": [[...]], ...}
            embeddings = data.get("embeddings") or data.get("embedding")
            if embeddings is None:
                raise ValueError(f"No 'embeddings' key in Ollama response: {list(data.keys())}")
            # Handle both list-of-lists and flat list
            vec = embeddings[0] if isinstance(embeddings[0], list) else embeddings
            if len(vec) != EMBED_DIM:
                raise ValueError(
                    f"Expected embedding dim {EMBED_DIM}, got {len(vec)}. "
                    "Is nomic-embed-text pulled in Ollama?"
                )
            return [float(v) for v in vec]

        try:
            return await asyncio.get_event_loop().run_in_executor(None, _do_request)
        except Exception as exc:
            raise RuntimeError(
                f"Embedding failed (Ollama at {url}): {exc}. "
                "Run: ollama pull nomic-embed-text"
            ) from exc

    # ── CRUD ──────────────────────────────────────────────────────────

    def _validate_domain(self, domain: str) -> None:
        if domain not in DOMAINS:
            valid = ", ".join(DOMAINS.keys())
            raise ValueError(f"Unknown memory domain '{domain}'. Valid: {valid}")

    async def store(
        self,
        domain: str,
        text: str,
        metadata: dict[str, Any] | None = None,
        doc_id: str | None = None,
    ) -> str:
        """Embed and store a memory entry. Returns the doc_id."""
        self._validate_domain(domain)

        if not _LANCEDB_AVAILABLE:
            logger.warning("store() called in stub mode — ignoring")
            return str(uuid.uuid4())

        vector = await self._embed(text)
        entry_id = doc_id or str(uuid.uuid4())
        meta_str = json.dumps(metadata or {})

        import pyarrow as pa  # local re-import for type safety
        table = self._tables[domain]
        batch = pa.table({
            "doc_id":     [entry_id],
            "text":       [text],
            "vector":     [vector],
            "metadata":   [meta_str],
            "created_at": [time.time()],
        })
        await table.add(batch)
        logger.debug("Stored memory '%s' in domain '%s'", entry_id, domain)
        return entry_id

    async def query(
        self,
        domain: str,
        query_text: str,
        n_results: int = 5,
        metadata_filter: str | None = None,
    ) -> list[MemoryResult]:
        """Semantic similarity search within a domain.

        Args:
            domain: One of spatial / behavioral / env_context / policy
            query_text: Natural language query
            n_results: Number of results to return
            metadata_filter: Optional LanceDB SQL WHERE clause on the metadata
                             column (e.g., "json_extract(metadata,'$.label') = 'dock'")
        """
        self._validate_domain(domain)

        if not _LANCEDB_AVAILABLE:
            return []

        vector = await self._embed(query_text)
        table = self._tables[domain]

        search = (
            table.vector_search(vector)
            .limit(n_results)
            .distance_type("cosine")
        )
        if metadata_filter:
            search = search.where(metadata_filter, prefilter=True)

        rows = await search.to_list()
        results: list[MemoryResult] = []
        for row in rows:
            try:
                meta = json.loads(row.get("metadata", "{}"))
            except json.JSONDecodeError:
                meta = {}
            results.append(MemoryResult(
                doc_id=row.get("doc_id", ""),
                text=row.get("text", ""),
                score=float(row.get("_distance", 0.0)),
                metadata=meta,
                created_at=float(row.get("created_at", 0.0)),
            ))
        return results

    async def delete(self, domain: str, doc_id: str) -> bool:
        """Delete a memory entry by ID. Returns True if successful."""
        self._validate_domain(domain)
        if not _LANCEDB_AVAILABLE:
            return False
        table = self._tables[domain]
        await table.delete(f"doc_id = '{doc_id}'")
        return True

    async def count(self, domain: str) -> int:
        """Return the number of entries in a domain table."""
        self._validate_domain(domain)
        if not _LANCEDB_AVAILABLE:
            return 0
        table = self._tables[domain]
        return await table.count_rows()

    # ── Summary ───────────────────────────────────────────────────────

    async def stats(self) -> dict[str, int]:
        """Return row count per domain table."""
        result: dict[str, int] = {}
        for domain in DOMAINS:
            result[domain] = await self.count(domain)
        return result
